In [100]:
import pandas as pd #importamos a principal biblioteca que utilizaremos
import matplotlib.pyplot as plt

In [80]:
#Importamos os dados estudados
clientes = pd.read_csv("Clientes.csv")
emprestimos = pd.read_csv("Emprestimos.csv")
pagamentos = pd.read_csv("Pagamentos.csv")

In [81]:
clientes.head()

   id_cliente       nome data_nascimento          cidade data_cadastro
0           1  Cliente_1      1959-12-28       Fortaleza    2018-04-13
1           2  Cliente_2      1974-09-04  Rio de Janeiro    2020-09-30
2           3  Cliente_3      1962-07-09       Fortaleza    2019-02-24
3           4  Cliente_4      1998-12-05        Salvador    2018-12-23
4           5  Cliente_5      1987-11-08       São Paulo    2018-05-11

In [82]:
emprestimos.head()

   id_emprestimo  id_cliente  valor  taxa_juros data_contratacao        status
0              1         411  40277       0.037       2021-05-31       quitado
1              2        2765  45236       0.022       2020-02-18  inadimplente
2              3        2190  12713       0.022       2022-05-04         ativo
3              4        3660  22275       0.022       2020-03-13  inadimplente
4              5         915  24412       0.039       2022-12-24  inadimplente

In [83]:
pagamentos.head()

   id_pagamento  id_emprestimo  valor_pago data_pagamento
0             1            964        5315     2023-05-12
1             2           1789        6693     2023-07-13
2             3           3796        5273     2022-12-29
3             4           3864        8332     2021-11-06
4             5             53        7720     2020-07-07

In [84]:
#Vamos criar uma nova planilha com os dados de

In [85]:
dado_cidades = pd.merge(emprestimos,clientes, how = "inner", on = "id_cliente")
dado_cidades

,id_emprestimo,id_cliente,valor,taxa_juros,data_contratacao,status,nome,data_nascimento,cidade,data_cadastro
0,1,411,40277,0.037,2021-05-31,quitado,Cliente_411,1972-06-09,Brasília,2023-02-15
1,2,2765,45236,0.022,2020-02-18,inadimplente,Cliente_2765,1953-08-23,Belo Horizonte,2018-12-03
2,3,2190,12713,0.022,2022-05-04,ativo,Cliente_2190,1989-05-30,Fortaleza,2023-06-30
3,4,3660,22275,0.022,2020-03-13,inadimplente,Cliente_3660,1958-01-09,Curitiba,2019-03-09
4,5,915,24412,0.039,2022-12-24,inadimplente,Cliente_915,1976-11-26,Rio de Janeiro,2022-03-22
...,...,...,...,...,...,...,...,...,...,...
4995,4996,2091,15244,0.028,2021-03-25,inadimplente,Cliente_2091,1958-07-22,Fortaleza,2024-09-04
4996,4997,1046,33181,0.046,2023-04-09,ativo,Cliente_1046,2003-08-24,Salvador,2023-05-17
4997,4998,1726,15050,0.015,2020-12-08,ativo,Cliente_1726,1950-06-08,Rio de Janeiro,2021-07-06
4998,4999,1877,40458,0.023,2023-02-14,ativo,Cliente_1877,1967-11-30,Fortaleza,2020-08-19
4999,5000,3597,1903,0.022,2021-02-27,inadimplente,Cliente_3597,1964-06-25,São Paulo,2018-02-20

In [91]:
cidades = {cidades: grupo for cidades, grupo in dado_cidades.groupby('cidade')}
chaves = list(cidades.keys())
total_emprestado = []
for i in range(len(chaves)):
    valor = int(cidades[chaves[i]]['valor'].sum())
    linha = {"cidade":chaves[i], "total_emprestado":valor}
    total_emprestado.append(linha)
valor_emprestado = pd.DataFrame(data=total_emprestado)

In [92]:
valor_emprestado

           cidade  total_emprestado
0  Belo Horizonte          17561732
1        Brasília          17539432
2        Curitiba          19104754
3       Fortaleza          19067165
4  Rio de Janeiro          17957809
5        Salvador          18021303
6       São Paulo          18678416